# Example values to deploy on EKS
# Update image tags to match what you pushed from Jenkins (e.g. BUILD_NUMBER)

app:
  mongoDb: streamingapp
  clientUrls: "http://REPLACE_WITH_FRONTEND_LB"
  jwtSecret:
    create: true
    value: "REPLACE_WITH_STRONG_SECRET"

services:
  auth:
    image:
      repository: "975050024946.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-auth"
      tag: "4"
  streaming:
    image:
      repository: "975050024946.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-streaming"
      tag: "4"
  admin:
    image:
      repository: "975050024946.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-admin"
      tag: "4"
  chat:
    image:
      repository: "975050024946.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-chat"
      tag: "4"
  frontend:
    image:
      repository: "975050024946.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-frontend"
      tag: "4"
