{{- if .Values.app.jwtSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamingapp.fullname" . }}-jwt
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.app.jwtSecret.value | b64enc | quote }}
{{- end }}
