{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
  selector:
    app.kubernetes.io/component: mongo
    {{- include "streamingapp.selectorLabels" . | nindent 4 }}
{{- end }}
